name: base_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  #for network calls
  connectivity_plus: ^3.0.2
  dio: ^4.0.6

  #For local db/storage/cache management
  shared_preferences: ^2.0.15
  objectbox: ^1.6.2
  objectbox_flutter_libs: any

  #local
  graphics:
    path: packages/graphics
  webview_flutter: ^3.0.4

  #other
  geolocator: ^9.0.2
  # flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true

  # flutter_icons:
  #   android: true
  #   ios: true
  #   remove_alpha_ios: true
  #   image_path: "assets/extras/icon.png"
  #   adaptive_icon_background: #ffffff
  #   adaptive_icon_foreground: #ffffff

  assets:
    - assets/png/
    - assets/svg/
    - assets/jpg/
