name: ecompasscare
version: 1.0.0+8
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  # cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  #local
  # graphics:
  #   path: packages/graphics

  #other
  webview_flutter: ^3.0.4
  geolocator: ^9.0.2
  lottie: ^2.2.0
  just_audio: ^0.9.31

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any
  shared_preferences: ^2.0.15
  #for network calls
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  #For local db/storage/cache management
  # objectbox: ^1.6.2
  # objectbox_flutter_libs: any

flutter:
  uses-material-design: true
  assets:
    # - assets/png/
    # - assets/svg/
    # - assets/jpg/
    - assets/lottie/
    - assets/audio/
