name: ecompasscare
# android
version: 2.2.4+241
# iOS
# version: 2.2.4+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  get: 4.6.5
  flutter:
    sdk: flutter

  webview_flutter: ^4.2.0
  geolocator: ^9.0.2
  lottie: ^2.2.0
  url_launcher: ^6.1.10
  onesignal_flutter: ^3.5.1
  http: ^0.13.5
  file_picker: ^5.2.7
  shared_preferences: ^2.1.0
  syncfusion_flutter_pdfviewer: ^21.1.39
  firebase_database: ^10.1.1
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.1
  photo_view: ^0.14.0
  upgrader: ^6.2.0
  # flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any
  #for network calls
  connectivity_plus: ^3.0.2
  dio: ^5.1.1
  #For local db/storage/cache management
  # objectbox: ^1.6.2
  # objectbox_flutter_libs: any

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/lottieSplash2.json

# flutter_icons:
#   android: "launcher_icon"
#   ios: false
#   image_path: "assets/extras/icon2.png"
#   adaptive_icon_foreground: "assets/extras/icon3.png"
#   adaptive_icon_background: "#6D4195"
#   min_sdk_android: 21 
#   web:
#     generate: false
#   windows:
#     generate: false
#   macos:
#     generate: false
# flutter clean && flutter pub get && flutter pub run flutter_launcher_icons