name: ecompasscare
version: 2.0.2+41
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  get: 4.6.5
  flutter:
    sdk: flutter

  webview_flutter: ^4.0.6
  geolocator: ^9.0.2
  lottie: ^2.2.0
  url_launcher: ^6.1.10
  onesignal_flutter: ^3.5.1
  package_info_plus: ^3.0.3
  http: ^0.13.5
  file_picker: ^5.2.7
  flutter_pdfview: ^1.3.0
  shared_preferences: ^2.1.0
  syncfusion_flutter_pdfviewer: ^21.1.39
  firebase_database: ^10.1.1
  firebase_core: ^2.10.0
  # flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any
  #for network calls
  connectivity_plus: ^3.0.2
  dio: ^5.1.1
  #For local db/storage/cache management
  # objectbox: ^1.6.2
  # objectbox_flutter_libs: any

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/audio/

# flutter_icons:
#   android: "launcher_icon"
#   ios: false
#   image_path_android: "assets/extras/icon1.png"
#   min_sdk_android: 21