// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCld2fr6wFLDg66e7PczTK-1sSrUJSUiL8',
    appId: '1:237487246699:android:ab1ee0f9e74401885ad02e',
    messagingSenderId: '237487246699',
    projectId: 'ecompass-care',
    databaseURL: 'https://ecompass-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecompass-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqn8-pQ6FeZUG4pjtUpUiIDqMm3mhJH0I',
    appId: '1:237487246699:ios:8ef6e2c7ae83c4455ad02e',
    messagingSenderId: '237487246699',
    projectId: 'ecompass-care',
    databaseURL: 'https://ecompass-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecompass-care.appspot.com',
    iosClientId: '237487246699-lftd2cd60nr7pm3rda8nfquvnq1s69ig.apps.googleusercontent.com',
    iosBundleId: 'com.sterlingAccuris.ios',
  );
}
