// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALYR75RjHj-71iZ0K1O51HJeE8PHlNcZs',
    appId: '1:229476156455:android:ffe1137e4f3b2b03',
    messagingSenderId: '229476156455',
    projectId: 'stearlingaccuries-b1b93',
    databaseURL: 'https://stearlingaccuries-b1b93.firebaseio.com',
    storageBucket: 'stearlingaccuries-b1b93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7M1BDap-XjpRhOegEk0eSiTcH3bCtMfQ',
    appId: '1:229476156455:ios:d942d2f312c05611',
    messagingSenderId: '229476156455',
    projectId: 'stearlingaccuries-b1b93',
    databaseURL: 'https://stearlingaccuries-b1b93.firebaseio.com',
    storageBucket: 'stearlingaccuries-b1b93.appspot.com',
    androidClientId: '229476156455-cooujqgc6dst7cj5g51gp246ius13enr.apps.googleusercontent.com',
    iosClientId: '229476156455-l7lk07d10br19q7fpjlh3nkietnevvbr.apps.googleusercontent.com',
    iosBundleId: 'com.sterlingAccuris.ios',
  );
}
